### ISSUE TITLE
No UltiSnips? :(

### ISSUE THREAD

**Issue by RyanSquared** [ctompkinson/vimball#2]
UltiSnips, as well as [the default snippets](https://github.com/honza/vim-snippets) repository, would be a great addition.

**Comment by ctompkinson** [comment]
I didn't know about this, I have a few shortcuts that have carried over from a personal snippet setup (:e on ~/snippets/) and this would be a much better solution.

I'll have a look at adding this!

**Comment by ctompkinson** [comment]
Added https://github.com/garbas/vim-snipmate and all the repositories listed in #3
